### ISSUE TITLE
Typo Figure 0.6

### ISSUE THREAD

**Issue by Leon0402** [dvgodoy/PyTorchStepByStep#1]
Hi there,

not sure if it's the right place, but it's the easiest one for me :) 

In Figure 0.6 in your book the diagrams has "w" on is x-axis instead of "b". 

Great book, hopefully there will be more content soon :)

**Comment by dvgodoy** [comment]
Thank you for letting me know, and for your kind words! I am glad you're enjoying the book :-)
I will fix this typo.
