### ISSUE TITLE
Chapter6 - Rock, Paper, Scissors - problem with dataset

### ISSUE THREAD

**Issue by newcastlea** [dvgodoy/PyTorchStepByStep#35]
Hi, if you have the same problem as me - the original link for downloading the Rock-Paper-Scissors dataset does not work in the function download_rps()
PyTorchStepByStep>>data_generation>>rps.py

So change this line there:
url = 'https://storage.googleapis.com/laurencemoroney-blog.appspot.com/{}'

To:
url = 'https://staff.utia.cas.cz/novozada/ml2/{}'

I downloaded the data from Kaggle:
https://www.kaggle.com/datasets/sanikamal/rock-paper-scissors-dataset

And stored them in the same way as the original dataset.

**Comment by dvgodoy** [comment]
Hi @newcastlea 

Thank you so much for pointing this out, and thank you for making the effort for providing an alternative :-)

I found the official URL directly from Google/TF, I guess they changed from Laurence's blog to TF itself.
The URL is [https://storage.googleapis.com/download.tensorflow.org/data](https://storage.googleapis.com/download.tensorflow.org/data), and I found it at 
[https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/datasets/rock_paper_scissors/rock_paper_scissors_dataset_builder.py
](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/datasets/rock_paper_scissors/rock_paper_scissors_dataset_builder.py

I've already committed the new URL to the repo, so it should work fine for everyone.
Once again, thank you!

Best,
Daniel

**Comment by newcastlea** [comment]
Thanks!
