### ISSUE TITLE
Structure of torchvision.models has changed

### ISSUE THREAD

**Issue by newyorker123** [dvgodoy/PyTorchStepByStep#37]
Hi,

I'm using torchvision 0.15.2. When I study chapter 7 transfer learning, I find that the structure of torchvision.models is changed and some code in the book now has problems. 

For example, the _model_urls_ method is deprecated and can't be imported. In addition, alexnet(pretrained=False) gives warning. Now, one should use the Weight object, like resnet50(weights=ResNet50_Weights.IMAGENET1K_V1).

Will you update chapter 7 in the near future to reflect these new features?

Thank you very much.

**Comment by dvgodoy** [comment]
Hi @newyorker123 ,

You're absolutely right, the code was broken for torchvision 0.15.2.

I fixed the notebook, making changes to reflect torchvision's new approach to loading weights, and added a small section explaining the changes, right before loading alexnet. This should make it easier to follow along, even if the book itself still describes the old way.

Thank you for your feedback and for supporting my work :-)

Best,
Daniel

**Comment by newyorker123** [comment]
Thank you so much!

**Comment by newyorker123** [comment]
> Hi @newyorker123 ,
> 
> You're absolutely right, the code was broken for torchvision 0.15.2.
> 
> I fixed the notebook, making changes to reflect torchvision's new approach to loading weights, and added a small section explaining the changes, right before loading alexnet. This should make it easier to follow along, even if the book itself still describes the old way.
> 
> Thank you for your feedback and for supporting my work :-)
> 
> Best, Daniel

Thank you so much!
