### ISSUE TITLE
PyTorchStepByStep is under advertised.

### ISSUE THREAD

**Issue by minertom** [dvgodoy/PyTorchStepByStep#8]
Danial, I wanted to let you know that I am really finding your Tutorial Series very helpful but you could be selling it a bit better.

1) I am finding the tutorial a fantastic help in terms of learning numpy.  Yes, the CS231 numpy tutorial give a good starting point but there is very little of practical use compared to what is in PyTorchStepByStep. 

2) Your tutorial provides a good learning point for matplotlib. I was forced to dig through the functions which generated the figures. I got everything working inside and outside of a python notebook. 

I just wanted to let you know how much I appreciate this tutorial.

Tom

**Comment by dvgodoy** [comment]
Hi Tom,

I am happy you're finding my book so helpful :-)
If I understood correctly, you're saying I should highlight more features of my book in its landing page?

I haven't put much thought into the advertisement part yet since there is still a sizeable amount of the content to be written, but any feedback is highly appreciated :-)

Best,
Daniel

**Comment by minertom** [comment]
Daniel,

Sorry it took so long for me to reply. I think that the best way to
characterize your book is to say that the examples can be used:

1) For a detailed view of pytorch and pytorch related topics such as
autograd and neural networks, etc.
2) A refresher for numpy and matplotlib, which are used to aid in the
examples implementing pytorch. (It is not a tutorial for numpy and
matplotlib, but if you follow how the examples are implemented, you can
learn a great deal)

You, personally, know a great deal about numpy and matplotlib but that does
not mean that a lot of your readers do. Truthfully, I have not found
tutorials on those topics that use the functions in as complicated a
fashion as you do. And that is a good thing. Tutorials only go so far.

I only made it into the first chapter before I had to take care of some
other issues. I am currently working on 9 tutorial series and yours is
first on the list.

I am sure that I will have some questions as things proceed.

Regards
Tom
